<?php

namespace ConsultationBundle\Repository;

/**
 * ConsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsRepository extends \Doctrine\ORM\EntityRepository
{
}
